# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WRGDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WRGDemo
  pod 'SDWebImage'

  target 'WRGDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WRGDemoUITests' do
    # Pods for testing
  end

end
